### ISSUE TITLE
Do we need the "Proceedings" in the navigation?

### ISSUE THREAD

**Issue by tvercaut** [MIDL-Conference/midl-website-2019#13]
We already have a navigation to the full papers (https://2019.midl.io/program/full-papers.html). We could maybe start the full paper page by a pointer to the PMLR proceeding? This would unclutter a bit the navigation pane.

Also, we will hopefully have an arXiv compendium for the extended abstracts. This would play a similar role as the PMLR proceedings but for extended abstracts rather than full papers:
https://arxiv.org/html/1907.08612

**Comment by nlessmann** [comment]
Makes sense, will remove it
