### ISSUE TITLE
Add a link to the video and reviews for each paper

### ISSUE THREAD

**Issue by tvercaut** [MIDL-Conference/midl-website-2019#14]
A bit of a tedious task but it would be nice for each of the paper to not only have a link to the paper but also to the video and the reviews:
https://2019.midl.io/program/full-papers.html

I have seen that the reviews are available by clicking on the paper title but this is a bit counterintuitive given that the link to the paper is made more explicit. As such as explicit "reviews" link would be helpful (as opposed to the videos, this part can be automated with a regexp).

**Comment by nlessmann** [comment]
Adding a "reviews" link is easy, the list of papers is rendered through a macro so only that needs to be adapted: https://github.com/MIDL-Conference/midl-website-theme/blob/master/layouts/_macros.html
