### ISSUE TITLE
Mention that extended abstracts are gathered as an abstract compendium

### ISSUE THREAD

**Issue by tvercaut** [MIDL-Conference/midl-website-2019#15]
Similar to how [PMLR](http://proceedings.mlr.press/v102/) is linked from the [full papers page](https://2019.midl.io/program/full-papers.html), it would be good to link to the (under construction) [arXiv compendium](https://arxiv.org/html/1907.08612) from the [extended abstract page](https://2019.midl.io/program/extended-abstracts.html).

**Comment by nlessmann** [comment]
Link has been added.

You can also make simple changes yourself if you want - if you edit the Markdown files in the "pages" directory, the website will be automatically rebuilt and published within a few minutes.
