### ISSUE TITLE
Twitter feed is nicer on the original website

### ISSUE THREAD

**Issue by tvercaut** [MIDL-Conference/midl-website-2019#6]
Currently, https://midl2019.netlify.com only shows one tweet and does not have the "Follow" link shown in http://2019.midl.io

**Comment by nlessmann** [comment]
Yes, I agree, but this is unfortunately difficult to fix. The original sites used a WordPress plugin, the new site uses what twitter itself provides for embedding a timeline.

Maybe I can add the follow button somehow manually. Showing multiple instead of just one tweet is certainly possible.

**Comment by tvercaut** [comment]
Thanks it looks better. One thing though. Can you also add a link to https://twitter.com/midl_conference next to the "follow" part
